---
title: A Night in Japan
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
email: a@nightinjapan.com
description: 'A blog about Japan. '
baseurl: 
url: 
twitter_username: BroadhurstGuy
github_username: guybroadhurst
theme: minima
plugins:
- jekyll-feed
